# Generated by Django 5.2.15 on 2026-06-13 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notice_version', models.CharField(default='2026-06-13', max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='events.event')),
            ],
            options={
                'ordering': ('-accepted_at',),
            },
        ),
    ]
