# Generated by Django 5.2.15 on 2026-06-13 13:16

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('faces', '0001_enable_pgvector'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('bbox', models.JSONField(help_text='[x1, y1, x2, y2] in original-image pixels')),
                ('det_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='events.event')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo')),
            ],
            options={
                'indexes': [models.Index(fields=['event'], name='faceemb_event_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='faceemb_hnsw_ip', opclasses=['vector_ip_ops'])],
            },
        ),
    ]
